### ISSUE TITLE
Cannot read property 'isUnion' of undefined

### ISSUE THREAD

**Issue by tankers746** [danielnixon/eslint-plugin-total-functions#24]
I receive an error from the no-array-destructuring rule at this line:
` const {
                                        items: [{ phone }]
                                    } = await response.json();`

The stack trace is:
```
[Error - 1:43:28 AM] TypeError: Cannot read property 'isUnion' of undefined
    at ArrayPattern (node_modules/eslint-plugin-total-functions/dist/rules/no-array-destructuring.js:44:51)
    at node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:635:23)
    at node_modules/eslint/lib/linter/linter.js:949:32
    at Array.forEach (<anonymous>)```

**Comment by danielnixon** [comment]
This should be fixed in v1.18.0. Thanks for reporting.
