### ISSUE TITLE
Does not work with ESLint v8

### ISSUE THREAD

**Issue by boris-petrov** [danielnixon/eslint-plugin-total-functions#504]
Updating ESLint to v8 leads to:

```
Oops! Something went wrong! :(

ESLint: 8.0.0

TypeError: Failed to load plugin 'total-functions' declared in '.eslintrc.js': Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/boris/project/frontend/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js:12:34)
    at Module._compile (/home/boris/project/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/home/boris/project/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/boris/project/frontend/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js:14:14)
    at Module._compile (/home/boris/project/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Comment by danielnixon** [comment]
New version published for ESLint 8.
