### ISSUE TITLE
prefer-immutable-types causes ESLint to crash on matrices

### ISSUE THREAD

**Issue by Tim-W-James** [danielnixon/eslint-plugin-total-functions#875]
```ts
const myFunction = (x: number[][]): string => {
  return 0;
};
```

Causes the rule to crash:

```
Oops! Something went wrong! :(

ESLint: 8.56.0

RangeError: Maximum call stack size exceeded
Occurred while linting .../src/index.ts:1
Rule: "functional/prefer-immutable-types"
    at TypeObject.hasOwn (<anonymous>)
    at Function.hasOwn (<anonymous>)
    at isTypeNode (.../is-immutable-type/dist/index.cjs:287:19)
    at .../is-immutable-type/dist/index.cjs:246:30
    at Array.map (<anonymous>)
    at typeArgumentsToString (.../is-immutable-type/dist/index.cjs:245:47)
    at TypeName.getNameWithArguments (.../is-immutable-type/dist/index.cjs:171:54)
    at .../is-immutable-type/dist/index.cjs:253:26
    at Array.map (<anonymous>)
    at typeArgumentsToString (.../node_modules/is-immutable-type/dist/index.cjs:245:47)
```

While this doesn't

```ts
```ts
const myFunction = (x: number[][]): string => {
  return 0;
};
```

**Comment by danielnixon** [comment]
Good catch, thanks.
